import Head from "next/head";

export default function Home() {
  const getArtist = async () => {
    const res = await fetch(
      "http://localhost:3000/api/artists/ckocxdb610000hwvbdt5yka2c"
    );
    const json = await res.json();
    console.log(json);
  };

  const getAlbum = async () => {
    const res = await fetch(
      "http://localhost:3000/api/albums/ckocxdzxj0000mcvbw2obv259"
    );
    const json = await res.json();
    console.log(json);
  };

  const getTrack = async () => {
    const res = await fetch(
      "http://localhost:3000/api/tracks/ckocxhc0c0000novbnso1e2jk"
    );
    const json = await res.json();
    console.log(json);
  };

  return (
    <div>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={getArtist}>Get Artist</button>
        <button onClick={getAlbum}>Get Album</button>
        <button onClick={getTrack}>Get Track</button>
      </main>
    </div>
  );
}
